# Generated by Django 3.0.8 on 2020-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NickName', models.CharField(max_length=30, verbose_name='Псевдоним')),
                ('Password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Аккаунт создан')),
                ('vip_status', models.DateTimeField(auto_now_add=True, verbose_name='Подписка')),
                ('Avatar', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
