# Generated by Django 3.0.8 on 2020-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NickName', models.CharField(max_length=30, unique=True, verbose_name='Псевдоним')),
                ('Password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('Password2', models.CharField(max_length=20, verbose_name='Повторите пароль')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('Created', models.DateTimeField(auto_now_add=True, verbose_name='Аккаунт создан')),
                ('vip_status', models.DateTimeField(auto_now_add=True, verbose_name='Подписка')),
            ],
        ),
    ]
