# Generated by Django 3.0.8 on 2020-07-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password2',
        ),
        migrations.AlterField(
            model_name='user',
            name='NickName',
            field=models.CharField(max_length=30, verbose_name='Псевдоним'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
    ]
