# Generated by Django 3.0.8 on 2020-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('Author', models.CharField(blank=True, max_length=30, verbose_name='Автор')),
                ('AuthorURL', models.CharField(max_length=500)),
                ('Header', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('ShortText', models.CharField(max_length=500, verbose_name='Короткий текст')),
                ('Rating', models.FloatField(verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=500)),
                ('UserURL', models.CharField(max_length=100)),
                ('UserNickName', models.CharField(max_length=30)),
                ('book_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
            ],
        ),
    ]
